/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicPublicRouteImport } from './routes/(public)/_public'
import { Route as publicPublicIndexRouteImport } from './routes/(public)/_public/index'
import { Route as publicPublicSearchRouteImport } from './routes/(public)/_public/search'
import { Route as publicPublicProfileRouteImport } from './routes/(public)/_public/profile'
import { Route as publicPublicExportRouteImport } from './routes/(public)/_public/export'
import { Route as publicPublicAccountRouteImport } from './routes/(public)/_public/account'
import { Route as publicPublicProfileIndexRouteImport } from './routes/(public)/_public/profile.index'
import { Route as publicPublicAuthIndexRouteImport } from './routes/(public)/_public/auth/index'
import { Route as publicPublicProfileProfileIdRouteImport } from './routes/(public)/_public/profile.$profileId'

const publicPublicRoute = publicPublicRouteImport.update({
  id: '/(public)/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPublicIndexRoute = publicPublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicPublicRoute,
} as any)
const publicPublicSearchRoute = publicPublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => publicPublicRoute,
} as any)
const publicPublicProfileRoute = publicPublicProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => publicPublicRoute,
} as any)
const publicPublicExportRoute = publicPublicExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => publicPublicRoute,
} as any)
const publicPublicAccountRoute = publicPublicAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => publicPublicRoute,
} as any)
const publicPublicProfileIndexRoute =
  publicPublicProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => publicPublicProfileRoute,
  } as any)
const publicPublicAuthIndexRoute = publicPublicAuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => publicPublicRoute,
} as any)
const publicPublicProfileProfileIdRoute =
  publicPublicProfileProfileIdRouteImport.update({
    id: '/$profileId',
    path: '/$profileId',
    getParentRoute: () => publicPublicProfileRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/account': typeof publicPublicAccountRoute
  '/export': typeof publicPublicExportRoute
  '/profile': typeof publicPublicProfileRouteWithChildren
  '/search': typeof publicPublicSearchRoute
  '/': typeof publicPublicIndexRoute
  '/profile/$profileId': typeof publicPublicProfileProfileIdRoute
  '/auth/': typeof publicPublicAuthIndexRoute
  '/profile/': typeof publicPublicProfileIndexRoute
}
export interface FileRoutesByTo {
  '/account': typeof publicPublicAccountRoute
  '/export': typeof publicPublicExportRoute
  '/search': typeof publicPublicSearchRoute
  '/': typeof publicPublicIndexRoute
  '/profile/$profileId': typeof publicPublicProfileProfileIdRoute
  '/auth': typeof publicPublicAuthIndexRoute
  '/profile': typeof publicPublicProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)/_public': typeof publicPublicRouteWithChildren
  '/(public)/_public/account': typeof publicPublicAccountRoute
  '/(public)/_public/export': typeof publicPublicExportRoute
  '/(public)/_public/profile': typeof publicPublicProfileRouteWithChildren
  '/(public)/_public/search': typeof publicPublicSearchRoute
  '/(public)/_public/': typeof publicPublicIndexRoute
  '/(public)/_public/profile/$profileId': typeof publicPublicProfileProfileIdRoute
  '/(public)/_public/auth/': typeof publicPublicAuthIndexRoute
  '/(public)/_public/profile/': typeof publicPublicProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/account'
    | '/export'
    | '/profile'
    | '/search'
    | '/'
    | '/profile/$profileId'
    | '/auth/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account'
    | '/export'
    | '/search'
    | '/'
    | '/profile/$profileId'
    | '/auth'
    | '/profile'
  id:
    | '__root__'
    | '/(public)/_public'
    | '/(public)/_public/account'
    | '/(public)/_public/export'
    | '/(public)/_public/profile'
    | '/(public)/_public/search'
    | '/(public)/_public/'
    | '/(public)/_public/profile/$profileId'
    | '/(public)/_public/auth/'
    | '/(public)/_public/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicPublicRoute: typeof publicPublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/_public': {
      id: '/(public)/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_public/': {
      id: '/(public)/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicPublicIndexRouteImport
      parentRoute: typeof publicPublicRoute
    }
    '/(public)/_public/search': {
      id: '/(public)/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof publicPublicSearchRouteImport
      parentRoute: typeof publicPublicRoute
    }
    '/(public)/_public/profile': {
      id: '/(public)/_public/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof publicPublicProfileRouteImport
      parentRoute: typeof publicPublicRoute
    }
    '/(public)/_public/export': {
      id: '/(public)/_public/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof publicPublicExportRouteImport
      parentRoute: typeof publicPublicRoute
    }
    '/(public)/_public/account': {
      id: '/(public)/_public/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof publicPublicAccountRouteImport
      parentRoute: typeof publicPublicRoute
    }
    '/(public)/_public/profile/': {
      id: '/(public)/_public/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof publicPublicProfileIndexRouteImport
      parentRoute: typeof publicPublicProfileRoute
    }
    '/(public)/_public/auth/': {
      id: '/(public)/_public/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof publicPublicAuthIndexRouteImport
      parentRoute: typeof publicPublicRoute
    }
    '/(public)/_public/profile/$profileId': {
      id: '/(public)/_public/profile/$profileId'
      path: '/$profileId'
      fullPath: '/profile/$profileId'
      preLoaderRoute: typeof publicPublicProfileProfileIdRouteImport
      parentRoute: typeof publicPublicProfileRoute
    }
  }
}

interface publicPublicProfileRouteChildren {
  publicPublicProfileProfileIdRoute: typeof publicPublicProfileProfileIdRoute
  publicPublicProfileIndexRoute: typeof publicPublicProfileIndexRoute
}

const publicPublicProfileRouteChildren: publicPublicProfileRouteChildren = {
  publicPublicProfileProfileIdRoute: publicPublicProfileProfileIdRoute,
  publicPublicProfileIndexRoute: publicPublicProfileIndexRoute,
}

const publicPublicProfileRouteWithChildren =
  publicPublicProfileRoute._addFileChildren(publicPublicProfileRouteChildren)

interface publicPublicRouteChildren {
  publicPublicAccountRoute: typeof publicPublicAccountRoute
  publicPublicExportRoute: typeof publicPublicExportRoute
  publicPublicProfileRoute: typeof publicPublicProfileRouteWithChildren
  publicPublicSearchRoute: typeof publicPublicSearchRoute
  publicPublicIndexRoute: typeof publicPublicIndexRoute
  publicPublicAuthIndexRoute: typeof publicPublicAuthIndexRoute
}

const publicPublicRouteChildren: publicPublicRouteChildren = {
  publicPublicAccountRoute: publicPublicAccountRoute,
  publicPublicExportRoute: publicPublicExportRoute,
  publicPublicProfileRoute: publicPublicProfileRouteWithChildren,
  publicPublicSearchRoute: publicPublicSearchRoute,
  publicPublicIndexRoute: publicPublicIndexRoute,
  publicPublicAuthIndexRoute: publicPublicAuthIndexRoute,
}

const publicPublicRouteWithChildren = publicPublicRoute._addFileChildren(
  publicPublicRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicPublicRoute: publicPublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
